version: '3'

services:
  nginx:
    image: nginx:1.17
    ports:
      - "80:8000"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - app

  db:
    image: mariadb:10.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: "app_db"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d

  app:
    build: ./docker/python
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code 
      - ./static:/static
    expose:
      - "8001"
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db